version: '3'
services:
  ml:
    container_name: ml-model
    restart: always
    build:
      context: ./ML
      dockerfile: Dockerfile
    command:
      - /bin/sh
      - -c
      - |
        # sleep 100
        python3 -u main.py
    ports:
      - 5000:5000
  db:
    container_name: mongodb
    env_file:
      - .env
    restart: always
    image: mongodb/mongodb-community-server
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017